target-version = "py312"
line-length = 120

[lint]
select = [
  "B",     # flake8-bugbear
  "D",     # pycodestyle
  "E",     # pycodestyle
  "F",     # pyflakes
  "I001",  # isort
  "Q",     # flake8-quotes
  "UP",    # pyupgrade
]
ignore = [
  # Don't require docstring in public modules/packages
  "D100", "D104",
  # Don't require docstring in classes
  "D101", "D106",
  # Don't require docstring in functions/methods
  "D102", "D103",
  # Don't require docstring in __init__ methods
  "D107",
]
task-tags = ["TODO", "FIXME", "XXX", "HACK"]

[lint.isort]
force-single-line = true
known-first-party = ["indico_patcher"]
section-order = ["future", "standard-library", "third-party", "indico", "first-party", "local-folder"]

[lint.isort.sections]
indico = ["indico"]

[lint.pydocstyle]
convention = "google"
